

animalIndex:
    path: /animal
    controller: App\Controller\AnimalController::index

home:
    path: /
    controller: App\Controller\IndexController::index

animal_cadastrar:
    path: /animal/cadastrar
    controller: App\Controller\AnimalController::adicionar
