

registrar:
    path: /registrar
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: GET   

animal_index:
    path: /animal
    controller: App\Controller\AnimalController::index

home:
    path: /
    controller: App\Controller\IndexController::index

animal_cadastrar:
    path: /animal/cadastrar
    controller: App\Controller\AnimalController::adicionar

animal_editar:
    path: /animal/editar/{id}
    controller: App\Controller\AnimalController::editar

animal_excluir:
    path: /animal/excluir/{id}
    controller: App\Controller\AnimalController::excluir


consumo_racao_index:
    path: /consumo
    controller: App\Controller\ConsumoRacaoController::index

consumo_racao_cadastrar:
    path: /consumo/cadastrar
    controller: App\Controller\ConsumoRacaoController::adicionar

consumo_racao_editar:
    path: /consumo/editar/{id}
    controller: App\Controller\ConsumoRacaoController::editar

consumo_racao_excluir:
    path: /consumo/excluir/{id}
    controller: App\Controller\ConsumoRacaoController::excluir

producao_leite_index:
    path: /producao
    controller: App\Controller\ProducaoLeiteController::index

producao_leite_cadastrar:
    path: /producao/cadastrar
    controller: App\Controller\ProducaoLeiteController::adicionar

producao_leite_editar:
    path: /producao/editar/{id}
    controller: App\Controller\ProducaoLeiteController::editar

producao_leite_excluir:
    path: /producao/excluir/{id}
    controller: App\Controller\ProducaoLeiteController::excluir




